include(
    "testsuite:vaadin14",
    "testsuite:vaadin21",
    "testsuite:testrun-vaadin14-stable",
    "testsuite:testrun-vaadin14-next",
    "testsuite:testrun-vaadin22",
    "testsuite:testrun-vaadin23",
    "testsuite:testrun-vaadin24",
)
